build: main.c
	gcc main.c game.c primitives.c collision.c fpsutils.c -o ../play -I include -framework SDL2 -F /Library/Frameworks -framework SDL2_ttf -F /Library/Frameworks -framework SDL2_image -F /Library/Frameworks
