build: main.c
	gcc main.c game.c primitives.c gameObject.c physics.c fpsutils.c background.c -o ../play -I include -framework SDL2 -F /Library/Frameworks -framework SDL2_ttf -F /Library/Frameworks -framework SDL2_image -F /Library/Frameworks
