build: main.c
	gcc main.c primitives.c gameObject.c physics.c fpsutils.c background.c playerShip.c laserBeam.c enemyShips.c timeUtils.c game.c -o ../play -I include -framework SDL2 -F /Library/Frameworks -framework SDL2_ttf -F /Library/Frameworks -framework SDL2_image -F /Library/Frameworks
